using System;
using BootstrapMvc.Core;
using BootstrapMvc.Paging;

namespace BootstrapMvc
{
    public static class PaginatorExtensions
    {
        #region Fluent

        public static IWriter2<T, PaginatorContent> Size<T>(this IWriter2<T, PaginatorContent> target, PaginatorSize value)
            where T :Paginator
        {
            target.Item.SizeValue = value;
            return target;
        }

        public static IWriter<PaginatorGenerator> Autogenerated<T>(this IWriter2<T, PaginatorContent> target)
            where T : Paginator
        {
            var res = target.Context.CreateWriter<PaginatorGenerator>();
            res.Item.Paginator = target.Item;
            return res;
        }

        public static IWriter<PaginatorGenerator> Autogenerated<T>(this IWriter2<T, PaginatorContent> target, int currentPage, int totalPages)
            where T : Paginator
        {
            return Autogenerated(target).CurrentPage(currentPage).TotalPages(totalPages);
        }

        #endregion

        #region Generating

        public static IWriter2<Paginator, PaginatorContent> Paginator(this IAnyContentMarker contentHelper)
        {
            return contentHelper.Context.CreateWriter<Paginator, PaginatorContent>();
        }

        public static IWriter2<Paginator, PaginatorContent> Paginator(this IAnyContentMarker contentHelper, PaginatorSize size)
        {
            return Paginator(contentHelper).Size(size);
        }

        public static PaginatorContent BeginPaginator(this IAnyContentMarker contentHelper)
        {
            return Paginator(contentHelper).BeginContent();
        }

        public static PaginatorContent BeginPaginator(this IAnyContentMarker contentHelper, PaginatorSize size)
        {
            return Paginator(contentHelper).Size(size).BeginContent();
        }

        #endregion
    }
}
